### ISSUE TITLE
Should I use Inheritance, Composition or an extension method?

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/CountPages#13]
During the development of the library Counter, I face an pattern problem. Some documents are archives. Pdf is not. Docx is. Odt is. You can unzip it to read what is inside.
To access to the number of a document's page, I had to.

My class Docx can read an archive. I added to Docx a private method `ReadArchive()`. Odt can read an archive. I decided to move my method to an extension method. It works. Fine we can move on. Well we could.
- I don't want to extend anything.
- Helpers are not really great from an OOP view point.
- Extension methods can bring some [troubles](http://blogs.developpeur.org/raptorxp/archive/2007/12/06/c-3-0-pourquoi-ne-faut-il-pas-utiliser-les-m-thodes-d-extension.aspx) [FR].

![Archivist throwing documents](http://www.cinemablend.com/images/gallery/s16616/april_fool_s_12386078904877.jpg)

Well, what can I do? I think about two alternatives. I could use Inheritance or Composition. Lets see some code and some logic.
## Helper

```
internal sealed class Doc : ADocument
{
    public Doc(Stream stream)
    {
        string content = Counter.Documents.Helper.Archivist.ReadArchive(stream);
        // do stuff with content like extract the page's count.
    }
}
```

I, as a document, ask an Archivist to read an archive for me.
## Composition

```
internal sealed class Doc : ADocument
{
    private static readonly Archivist Archivist = new Archivist();

    public Doc(Stream stream)
    {
        string content = Archivist.ReadArchive(stream);
        // do stuff with content like extract the page's count.
    }
}
```

I, as a document, own an Archivist to read an archive for me.
## Inheritance

```
internal sealed class Doc : ADocument, Archivist
{
    public Doc(Stream stream)
    {
        string content = ReadArchive(stream);
        // do stuff with content like extract the page's count.
    }
}
```

I, as a document, am also an Archivist. I know how to read an archive.

Multiple inheritance is considered armful. I can understand why ([post about this](http://programmers.stackexchange.com/a/218463/121841)), but not in this case. Can you enlight me?

We cant use multiple inheritance in C#, but we can [simulate](http://www.codeproject.com/Articles/10072/Simulated-Multiple-Inheritance-Pattern-for-C) it. I don't want to add complexity to this project and I dot want to use an antipattern.

I am going to move to the composition pattern. In this case, should I?

**Comment by aloisdg** [comment]
I just spoke with @nvareille and we found a solution :)

We used to have :

![old uml diagram](http://yuml.me/diagram/scruffy;dir:LR/class/%5BIDocument%5D-%3E%5BADocument%5D,%20%5BADocument%5D-%3E%5BPdf%5D,%20%5BADocument%5D-%3E%5BDoc%5D,%20%5BADocument%5D-%3E%5BOdt%5D.png)

And we are moving to :

![new uml diagram](http://yuml.me/diagram/scruffy;dir:LR/class/%5BIDocument%5D-%3E%5BADocument%5D,%20%5BADocument%5D-%3E%5BPdf%5D,%20%5BADocument%5D-%3E%5BAArchive%5D,%20%5BAArchive%5D-%3E%5BDoc%5D,%20%5BAArchive%5D-%3E%5BOdt%5D.png)

We are going to use inheritance in a better way that the one I tought. Hope you approve it.

**Comment by nvareille** [comment]
Glad to be helpful on this case !
